name: "Terraform"

on: 
 push:
  branch: main

job:
  terraform:
   name: "Terraform"
   runs-on: Ubuntu-latest
   env:
    AWS_ACCESS_KEY_ID = ${{ secret.AWS_ACCESS_KEY_ID }}
    AWS_SERCERT_ACCESS_KEY = ${{ secret.AWS_SERCERT_ACCESS_KEY}}
   defaults:
    run: 
     working-directory: AWS-VPC-TERRAFORM\
   steps:
    - names: Checkout
      uses: actions/checkout@v2


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
       terraform_version: 1.0.1
       terraform_wrapper: false

    - name: Terraform Format
      id: fmt   
      run: terraform fmt -check 

    - name: Terraform init
      id: init  
      run: terraform init
    
    - name: Terraform Plan
      id: plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
